language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - clang
      - g++-4.8

before_install:
  - export CORECONFIG="g++-4.8";
  - echo $CORECONFIG
  - make -C src
  - make -C tests

script:
  - cd tests
  - ./run

compiler:
  - gcc

os:
  - linux
