dist: trusty
language: c
sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

before_install:
  - export COREIRCONFIG="g++-4.9";
  - export LD_LIBRARY_PATH=`pwd`/lib:$LD_LIBRARY_PATH
  - make -j2 install

script:
  - make test

compiler:
  - gcc

os:
  - linux
