language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - clang
      - g++-4.9

before_install:
  - export CORECONFIG="g++-4.9";
  - echo $CORECONFIG
  - make -C src
  - make -C src ../build/coreir.so  # For bindings tests
  - make -C tests
  - sudo pip install pytest
  - sudo pip install -e bindings/python

script:
  - cd tests
  - ./run
  - pytest  # Test python bindings

compiler:
  - gcc

os:
  - linux
