dist: trusty
language: c
sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

before_install:
  - export COREIRCONFIG="g++-4.9";
  - sudo make -j 2 install

script:
  - make installtest
  - sudo make uninstall
  - export LD_LIBRARY_PATH=`pwd`/lib:$LD_LIBRARY_PATH
  - make test

compiler:
  - gcc

os:
  - linux
