dist: trusty
language: c
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
    - python-virtualenv
before_install:
- export COREIRCONFIG="g++-4.9";
- sudo make -j install
- make release
script:
- make installtest
- sudo make uninstall
- export LD_LIBRARY_PATH=`pwd`/lib:$LD_LIBRARY_PATH
- make test
compiler:
- gcc
os:
- linux
deploy:
  provider: releases
  api_key:
    secure: ov1UJzIPDhQpIFlItxEI1d+1YZmW2UU83cXZTLm+Wl4m+Uanab1r3s9UakGW8OqwTDmKu1JHba876lC1YWcO6K9o6iAx8YVqTFKh89kOGs1V2vfkgMHVkV+x+AcxwUJJDOv0J2KCntLU6O7babm5peLMkctqsyfiOHK4muedKxpMLG6ZFyKit42yqXp2uLKJF7SvLtSBV7hSFST8fnt05Whxu4m8YP5qAQEKLkfo77dPS4/RXjo02ac5mTVEXklB8xvNvuPDNq1rWS/+0H83XMO3dJcDKYD6hOV48/pE17Imli6SEVMUwXsTAoGHRocfKXQRZS36mMD139YhDydZTckmlDVMN1P/+yKzsGg58cX9Z6AAp0fu2i/5myqbqH/m14JBlyZrvL8KuDL1uJvzwr6mbrlQGphOAOoGLNN3ziPAmJRdw4y73UCJjaK5I875O+YtCDmgadtlZp3QfTCUj9u/WsS8lFKv72tggWLf2gri3krfUQaFxHni2gMJY2DMeqFXh6g5/QY+naCoYQ2tFt6ORZZiB7K3iLe7hSh3BPq7/gvC/BV+pjaQMvH3YA8K9jDhn+SObhykR1yB2EAi8JpjOm2HfSHK2wvjPlwzsQQ2/0K9j8SwzChMJ+4s9gbPGOjiYatAMXIl61OlT8KkTrDfJp+lOMasLBaQDMYthfs=
  file: "coreir.tar.gz"
  on:
    repo: rdaly525/coreir
