language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - sudo apt-get -qq update
  - make -C src
  - make -C tests

script:
  - cd tests
  - ./run
