dist: trusty
language: c
sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

before_install:
  - export COREIRCONFIG="g++-4.9";
  - export LD_LIBRARY_PATH=`pwd`/bin;
  - make -C src build/coreir.so  # For bindings tests
  - make -C lib so #will build all shared libraries
  - make -C tests
  - pip install pytest
  - pip install -e bindings/python

script:
  - cd tests
  - ./run 
  - pytest  # Test python bindings

compiler:
  - gcc

os:
  - linux
