language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - clang
      - g++-4.8

before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - make -C src echo
  - make -C src
  - make -C tests

script:
  - cd tests
  - ./run

os:
  - linux
